### PR TITLE
memory improvement, fix python update offsets, change compiler params

### PR DESCRIPTION
**Pull request by notcpuid**
use native api instead of standard winapi
fix update_offsets.py
add multiprocessor compilations
change linking method

Judging by the tests, I can say with confidence that using the Native API directly is much faster in operation than WinAPI.

### CODE REVIEW

**Comment by IMXNOOBX** [comment]
Looks promising, i will give it a look later! Thanks for your contribution!

**Comment by ifBars** [comment]
> use native api instead of standard winapi
> 
> fix update_offsets.py
> 
> add multiprocessor compilations
> 
> change linking method
> 
> 
> 
> Judging by the tests, I can say with confidence that using the Native API directly is much faster in operation than WinAPI.

Nice changes! Everything looks good, will test performance later!

**Review by ifBars — COMMENTED** [review]
Tested it, works great, didn't see a huge performance increase, but it is definitely there. Not sure what exactly changed in update_offsets.py as I don't know python. Thanks for your contribution nonetheless.

**Review by IMXNOOBX — APPROVED** [review]
Thanks for your contribution!

**Comment by IMXNOOBX** [comment]
@notcpuid is there any reason you changed in the python script the path of the file? it should only work only by adding the full relative path

**Comment by notcpuid** [comment]
@IMXNOOBX Regarding the Python script, I had an error when searching for the path to the file. I forgot to remove this change. Sorry.

**Pull request merged**
