### PR TITLE
Add player armor, weapon name, $ amount, isDefusing tag, an armor bar, and C4 ESP

### PR DESCRIPTION
**Pull request by ifBars**
I got a little bit lazy here, so there may be some cleanup needed. As the title mentions, this adds back armor, creates a second bar for armor, and also displays the weapon name and if the player is defusing, it displays text "Player is defusing".

One example of cleanup is the fact that weapon names all display "weapon_name" so removing "weapon_" before rendering the name would be ideal

*Side Note - A better way to implement a head tracker is by using bone array, finding head bone, and rendering from that position, but I am too lazy to implement that lol*

Edit: This also updates the game to work with the latest update 10/19/23

image
image
image

### CODE REVIEW

**Comment by IMXNOOBX** [comment]
Sorry for the delay. I will try to review the changes soon.

**Comment by ifBars** [comment]
> Owner

No worries, sounds good

**Comment by IMXNOOBX** [comment]
Im having issues trying your pull request, have you tested it in the latest game version?

**Comment by IMXNOOBX** [comment]
> > Sorry for the delay. I will try to review the changes soon.
> 
> No worries, sounds good
> 
> _Not sure why offsets are conflicting but should be an easy fix_ Edit: Fixed by just replacing with new offsets
> 
> **If you need some help maintaining the repo, and feel comfortable giving me write permission, I'd be happy to help keep it updated, and possibly review any pull requests that I can. Just an offer, up to you :), I will continue to provide updates via pull requests either way.**

That would be great, can you contact me though discord again and we talk about it

**Comment by ifBars** [comment]
> > > Sorry for the delay. I will try to review the changes soon.
> 
> > 
> 
> > No worries, sounds good
> 
> > 
> 
> > _Not sure why offsets are conflicting but should be an easy fix_ Edit: Fixed by just replacing with new offsets
> 
> > 
> 
> > **If you need some help maintaining the repo, and feel comfortable giving me write permission, I'd be happy to help keep it updated, and possibly review any pull requests that I can. Just an offer, up to you :), I will continue to provide updates via pull requests either way.**
> 
> 
> 
> That would be great, can you contact me though discord again and we talk about it

Yea, my fork was working 100% fine just an hour ago. I could probably help you debug the issue. I don't think I have you added on discord though.

**Review by IMXNOOBX — APPROVED** [review]
Everything looks great, thanks for your contribution

**Pull request merged**
