### PR TITLE
Reduce Overlay delay (Smoother esp)

### PR DESCRIPTION
**Pull request by Marshall-67**

### CODE REVIEW

**Comment by Marshall-67** [comment]
I'm sure this could be improved alot. but im very new at this

**Comment by IMXNOOBX** [comment]
Thanks for your suggestions, i will review it tomorrow!

**Comment by IMXNOOBX** [comment]
I see two mayor problems, 
1. If you reduce the delay of the thread it will be reading faster from memory making it consume more resources, lines: 
https://github.com/IMXNOOBX/cs2-external-esp/blob/40d249274e89d1efd802464385da12f9c187214f/memory-external/hacks/hack.hpp#L124-L127
2. You should get the fps from the main screen where the game is supposed to run.

After testing it with the old version for a while i could not notice any diference in the performace. The issue might be noticable for users with a frame rate superior to 60 wich might be why the users are complaining for, i dont have any screen with more that 60fps. if you do could you make a performance testing and if so could you record it please. 

Im looking forward to your response and more contributions!

**Comment by Marshall-67** [comment]
I'd be happy to record a video. ill do it once i have some spare time

Thank you. and yes it would probably come from users running at a higher fps i'd assume

**Pull request closed without merging**
