### PR TITLE
Add toggleable things: rainbow effect, armor display, distance display, and a somewhat working head tracker

### PR DESCRIPTION
**Pull request by ifBars**
image
image

Toggleable using F7, this rainbow effect is integrated into the config file, with an adjustable speed float to allow for faster or slower fading through colors. Higher the rainbow_speed, faster the effect, & vice versa. Armor is toggleable with F8, and player distances with F9. Head tracker toggleable with F10.

### CODE REVIEW

**Comment by IMXNOOBX** [comment]
Changes look promising! sorry for the delay, ive been really busy. I will review the changes in later when i get to the pc. Thanks for your contribution!

**Comment by ifBars** [comment]
> Changes look promising! sorry for the delay, ive been really busy. I will review the changes in later when i get to the pc. Thanks for your contribution!

No worries at all! Thanks for your reply, you might find that the head tracker is a bit janky. I'm still new to C++, so it was the best I could get it lol.

**Comment by IMXNOOBX** [comment]
I will make some changes such as removing the raimbow mode and adding in the configuration the hability to modify the colors for some items and some more, but great chages over all.

**Comment by ifBars** [comment]
> I will make some changes such as removing the raimbow mode and adding in the configuration the hability to modify the colors for some items and some more, but great chages over all.

Thanks! I look forward to trying to contribute more. I have been working on trying to get the weapon name, however I have been unsuccessful. I tried using WeaponHash but that seems to be non unique to the weapon name. I then tried using pClippingWeapon using the method from [TKazer's External](https://github.com/TKazer/CS2_External) but could not successfully read the value.

**Pull request merged**
